/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  PROVIDERS: () => PROVIDERS,
  default: () => VaultAgentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// view.ts
var import_obsidian2 = require("obsidian");

// agent.ts
async function chatCompletion(cfg, messages, tools, h) {
  const url = cfg.baseUrl.replace(/\/+$/, "") + "/chat/completions";
  const headers = {
    "Content-Type": "application/json",
    Authorization: "Bearer " + cfg.apiKey
  };
  const fnTools = tools.length ? tools.map((t2) => ({ type: "function", function: { name: t2.name, description: t2.description, parameters: t2.parameters } })) : [];
  const nativeTools = cfg.nativeSearch?.tools ?? [];
  let withNative = nativeTools.length > 0 || cfg.nativeSearch?.extraBody !== void 0;
  const buildPayload = (include) => {
    const allTools = include ? [...fnTools, ...nativeTools] : fnTools;
    return {
      // Spread first so vendor extras can never clobber model/messages.
      ...include ? cfg.nativeSearch?.extraBody ?? {} : {},
      model: cfg.model,
      messages,
      temperature: cfg.temperature ?? 0.7,
      max_tokens: cfg.maxTokens ?? 8192,
      stream: true,
      tools: allTools.length ? allTools : void 0
    };
  };
  const turn = { content: null, reasoning: null, toolCalls: [] };
  const sendStream = async () => {
    if (!h.fetchImpl)
      throw new Error("no streaming fetch implementation provided");
    const res = await h.fetchImpl(url, {
      method: "POST",
      headers,
      body: JSON.stringify(buildPayload(withNative)),
      signal: h.signal
    });
    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      throw new Error(`HTTP ${res.status}: ${truncate(errText, 500)}`);
    }
    if (!res.body)
      throw new Error("empty response body");
    await consumeSse(res.body, (data) => applyChunk(data, turn, h));
  };
  try {
    try {
      await sendStream();
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      const idle = turn.content === null && turn.toolCalls.length === 0;
      const rejected = /^HTTP (400|404|422)\b/.test(message);
      if (!withNative || !rejected || !idle || h.signal?.aborted)
        throw e;
      withNative = false;
      h.onSearchFallback?.(message);
      await sendStream();
    }
  } catch (e) {
    if (h.fallbackPost && !h.signal?.aborted) {
      const out = await h.fallbackPost(url, headers, JSON.stringify({ ...buildPayload(withNative), stream: false }));
      if (out.status >= 400)
        throw new Error(`HTTP ${out.status}: ${truncate(out.body, 500)}`);
      applyChunk(out.body || "{}", turn, h, true);
    } else {
      throw e;
    }
  }
  return turn;
}
function asRecord(v) {
  return v !== null && typeof v === "object" ? v : null;
}
function applyChunk(payload, turn, h, nonStream = false) {
  if (!payload || payload === "[DONE]")
    return;
  let parsed;
  try {
    parsed = JSON.parse(payload);
  } catch {
    return;
  }
  const data = asRecord(parsed);
  if (!data)
    return;
  const choices = Array.isArray(data.choices) ? data.choices : [];
  const choice = asRecord(choices[0]);
  if (!choice)
    return;
  const raw = nonStream ? choice.message : choice.delta;
  const delta = asRecord(raw) ?? {};
  const content = delta.content;
  if (typeof content === "string" && content.length) {
    turn.content = (turn.content ?? "") + content;
    h.onText?.(content);
  }
  const reasoning = delta.reasoning_content;
  if (typeof reasoning === "string" && reasoning.length) {
    turn.reasoning = (turn.reasoning ?? "") + reasoning;
    h.onReasoning?.(reasoning);
  }
  const toolCallsRaw = Array.isArray(delta.tool_calls) ? delta.tool_calls : [];
  if (toolCallsRaw.length) {
    for (const rawTc of toolCallsRaw) {
      const tc = asRecord(rawTc);
      if (!tc)
        continue;
      const fn = asRecord(tc.function);
      const idx = typeof tc.index === "number" ? tc.index : 0;
      let target = turn.toolCalls[idx];
      if (!target) {
        target = {
          id: typeof tc.id === "string" ? tc.id : "",
          type: "function",
          function: { name: typeof fn?.name === "string" ? fn.name : "", arguments: "" }
        };
        turn.toolCalls[idx] = target;
      }
      if (typeof tc.id === "string" && tc.id)
        target.id = tc.id;
      if (typeof fn?.name === "string" && fn.name)
        target.function.name = fn.name;
      if (typeof fn?.arguments === "string")
        target.function.arguments += fn.arguments;
    }
    h.onToolCallDelta?.(turn.toolCalls.filter(Boolean));
  }
}
async function consumeSse(body, cb) {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done)
      break;
    buf += decoder.decode(value, { stream: true });
    let nl;
    while ((nl = buf.indexOf("\n")) >= 0) {
      const line = buf.slice(0, nl).replace(/\r$/, "");
      buf = buf.slice(nl + 1);
      if (line.startsWith("data:"))
        cb(line.slice(5).trim());
    }
  }
  const rest = buf.trim();
  if (rest.startsWith("data:"))
    cb(rest.slice(5).trim());
}
async function runAgentLoop(opts) {
  const maxIter = opts.maxIterations ?? 12;
  let hitCap = false;
  let reasoning = "";
  for (let i = 0; i < maxIter; i++) {
    const turn = await chatCompletion(opts, opts.messages, opts.tools, {
      onText: opts.onText,
      onReasoning: opts.onReasoning,
      onSearchFallback: opts.onSearchFallback,
      signal: opts.signal,
      fetchImpl: opts.fetchImpl,
      fallbackPost: opts.fallbackPost
    });
    if (turn.reasoning)
      reasoning += (reasoning ? "\n" : "") + turn.reasoning;
    const calls = turn.toolCalls.filter(Boolean);
    if (!calls.length) {
      return { text: turn.content ?? "", reasoning, hitCap: false };
    }
    opts.messages.push({
      role: "assistant",
      content: turn.content ?? null,
      tool_calls: calls
    });
    for (const call of calls) {
      opts.onToolStart?.(call);
      let result = { ok: false, content: "blocked before execution" };
      try {
        if (opts.passthroughTools?.includes(call.function.name)) {
          result = { ok: true, content: call.function.arguments || "{}" };
        } else {
          const args = JSON.parse(call.function.arguments || "{}");
          const def = opts.tools.find((t2) => t2.name === call.function.name);
          if (def?.x_write && opts.confirmWrite && !await opts.confirmWrite(`${call.function.name}: ${truncate(JSON.stringify(args), 200)}`)) {
            result = { ok: false, content: "USER_DENIED" };
          } else {
            result = await opts.executor.execute(call.function.name, call.function.arguments);
          }
        }
      } catch (e) {
        result = { ok: false, content: "tool error: " + (e instanceof Error ? e.message : String(e)) };
      }
      opts.onToolDone?.(call, result);
      opts.messages.push({
        role: "tool",
        tool_call_id: call.id,
        content: truncate(result.content, 2e4)
      });
    }
    hitCap = true;
  }
  return { text: "", reasoning: "", hitCap };
}
function truncate(s, n) {
  if (s.length <= n)
    return s;
  return s.slice(0, n) + `\u2026 [truncated, ${s.length} chars total]`;
}
function normalizeReasoning(text) {
  return text.replace(/\r\n?/g, "\n").replace(/[ \t]+/g, " ").replace(/ ?\n ?/g, "\n").replace(/^([-*_]) *(?:\1 *){2,}$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
}

// proxyFetch.ts
function parseProxy(proxy) {
  let raw = proxy.trim();
  if (/^socks/i.test(raw)) {
    throw new Error("SOCKS proxies are not supported \u2014 use an HTTP proxy, e.g. http://127.0.0.1:9000");
  }
  raw = raw.replace(/^https?:\/\//i, "");
  const m = /^(?:([^@/:]+):([^@/]*)@)?([a-zA-Z0-9.\-_]+):(\d+)$/.exec(raw);
  if (!m) {
    throw new Error(`invalid proxy address: ${proxy} (expected host:port, e.g. 127.0.0.1:9000)`);
  }
  const conf = { host: m[3], port: Number(m[4]) };
  if (m[1] !== void 0) {
    conf.auth = "Basic " + btoa(`${m[1]}:${m[2] ?? ""}`);
  }
  return conf;
}
function toError(e) {
  return e instanceof Error ? e : new Error(String(e));
}
function nodeRequire(mod) {
  const w = typeof window !== "undefined" ? window : void 0;
  const req = w?.require;
  if (!req) {
    throw new Error("Node modules are unavailable here \u2014 the local proxy feature requires Obsidian desktop.");
  }
  return req(mod);
}
function proxyHeaders(conf, extra) {
  return { ...extra, ...conf.auth ? { "Proxy-Authorization": conf.auth } : {} };
}
function forwardRequest(conf, url, init) {
  return new Promise((resolve, reject) => {
    const http = nodeRequire("http");
    const u = new URL(url);
    const req = http.request({
      host: conf.host,
      port: conf.port,
      method: init.method,
      path: url,
      headers: proxyHeaders(conf, { ...init.headers, Host: u.host })
    }, (res) => resolve(res));
    req.on("error", (err) => reject(toError(err)));
    if (init.signal) {
      init.signal.addEventListener("abort", () => req.destroy(new Error("aborted")), { once: true });
    }
    if (init.body)
      req.write(init.body);
    req.end();
  });
}
function connectAndRequest(conf, url, init) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const port = Number(u.port) || 443;
    const http = nodeRequire("http");
    const https = nodeRequire("https");
    const conn = http.request({
      host: conf.host,
      port: conf.port,
      method: "CONNECT",
      path: `${u.hostname}:${port}`,
      headers: proxyHeaders(conf, { Host: `${u.hostname}:${port}` })
    });
    conn.on("error", (err) => reject(toError(err)));
    if (init.signal) {
      init.signal.addEventListener("abort", () => conn.destroy(new Error("aborted")), { once: true });
    }
    conn.on("connect", (...args) => {
      const res = args[0];
      const socket = args[1];
      if (res.statusCode !== 200) {
        res.destroy();
        reject(new Error(`proxy CONNECT failed with status ${res.statusCode}`));
        return;
      }
      const tlsReq = https.request({
        hostname: u.hostname,
        port,
        path: u.pathname + u.search,
        method: init.method,
        headers: init.headers,
        servername: u.hostname,
        createConnection: () => socket
      }, (res2) => resolve(res2));
      tlsReq.on("error", (err) => reject(toError(err)));
      if (init.signal) {
        init.signal.addEventListener("abort", () => tlsReq.destroy(new Error("aborted")), { once: true });
      }
      if (init.body)
        tlsReq.write(init.body);
      tlsReq.end();
    });
    conn.end();
  });
}
function toStream(nodeRes) {
  return new ReadableStream({
    start(controller) {
      nodeRes.on("data", (...args) => {
        try {
          controller.enqueue(args[0]);
        } catch {
        }
      });
      nodeRes.on("end", () => {
        try {
          controller.close();
        } catch {
        }
      });
      nodeRes.on("error", (...args) => {
        try {
          controller.error(args[0] instanceof Error ? args[0] : new Error("stream error"));
        } catch {
        }
      });
    },
    cancel() {
      nodeRes.destroy();
    }
  });
}
function makeProxyFetch(proxy) {
  const conf = parseProxy(proxy);
  return async (url, init) => {
    const nodeRes = new URL(url).protocol === "https:" ? await connectAndRequest(conf, url, init) : await forwardRequest(conf, url, init);
    const status = nodeRes.statusCode ?? 0;
    let bodyUsed = false;
    let bodyStream = null;
    const result = {
      ok: status >= 200 && status < 300,
      status,
      text: () => {
        if (bodyUsed)
          throw new Error("response body already consumed");
        bodyUsed = true;
        return new Promise((resolve, reject) => {
          let out = "";
          nodeRes.setEncoding("utf8");
          nodeRes.on("data", (...args) => {
            out += String(args[0]);
          });
          nodeRes.on("end", () => resolve(out));
          nodeRes.on("error", (...args) => reject(args[0] instanceof Error ? args[0] : new Error("stream error")));
        });
      },
      body: null
    };
    Object.defineProperty(result, "body", {
      get: () => {
        if (bodyUsed)
          return null;
        bodyUsed = true;
        if (!bodyStream)
          bodyStream = toStream(nodeRes);
        return bodyStream;
      }
    });
    return result;
  };
}

// history.ts
function newSessionId() {
  return `${Date.now().toString(36)}-${randomHex(8)}`;
}
function randomHex(length) {
  const webCrypto = typeof crypto !== "undefined" ? crypto : null;
  if (webCrypto && typeof webCrypto.getRandomValues === "function") {
    const bytes = new Uint8Array(Math.ceil(length / 2));
    webCrypto.getRandomValues(bytes);
    return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("").slice(0, length);
  }
  let out = "";
  for (let i = 0; i < length; i++)
    out += Math.floor(Math.random() * 16).toString(16);
  return out;
}
var HistoryRecorder = class {
  /**
   * @param start seq/turn to continue from — pass `sessionCursor()` when
   * resuming an existing session so numbering does not restart at 1.
   */
  constructor(adapter, path, sessionId, meta, start = { seq: 0, turn: 0 }) {
    this.adapter = adapter;
    this.path = path;
    this.sessionId = sessionId;
    this.meta = meta;
    /** Tail of the append chain; keeps lines whole when events arrive rapidly. */
    this.pending = Promise.resolve();
    this.seq = start.seq;
    this.turn = start.turn;
  }
  user(text) {
    this.turn++;
    this.write({ type: "user", role: "user", content: text });
  }
  assistant(text, reasoning) {
    this.write({ type: "assistant", role: "assistant", content: text, reasoning: reasoning || void 0 });
  }
  toolCall(call) {
    this.write({
      type: "tool_call",
      role: "tool",
      tool: call.function.name,
      callId: call.id,
      args: call.function.arguments
    });
  }
  toolResult(call, result, durationMs) {
    this.write({
      type: "tool_result",
      role: "tool",
      tool: call.function.name,
      callId: call.id,
      ok: result.ok,
      content: result.content,
      durationMs: Math.max(0, Math.round(durationMs))
    });
  }
  error(message) {
    this.write({ type: "error", role: "assistant", content: message });
  }
  /** Resolves once every queued line has been handed to the adapter. */
  flush() {
    return this.pending;
  }
  /**
   * Appends are chained rather than fired in parallel: two overlapping
   * `append` calls could otherwise interleave and corrupt a JSONL line.
   * Logging must never break the chat, so failures are swallowed.
   */
  write(partial) {
    this.seq++;
    const event = {
      ...this.meta(),
      id: randomHex(16),
      ts: Date.now(),
      iso: (/* @__PURE__ */ new Date()).toISOString(),
      session: this.sessionId,
      seq: this.seq,
      turn: this.turn,
      ...partial
    };
    const line = JSON.stringify(event) + "\n";
    this.pending = this.pending.then(() => this.adapter.append(this.path, line)).catch(() => void 0);
  }
};
function parseHistory(text) {
  const events = [];
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed)
      continue;
    try {
      const parsed = JSON.parse(trimmed);
      const event = parsed;
      if (event && typeof event === "object" && typeof event.session === "string") {
        events.push(event);
      }
    } catch {
    }
  }
  return events;
}
function summarizeSessions(events, query = "") {
  const needle = query.trim().toLowerCase();
  const bySession = /* @__PURE__ */ new Map();
  for (const event of events) {
    const bucket = bySession.get(event.session);
    if (bucket)
      bucket.push(event);
    else
      bySession.set(event.session, [event]);
  }
  const out = [];
  for (const [id, bucket] of bySession) {
    const ordered = [...bucket].sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0));
    let hit;
    if (needle) {
      const match = ordered.find((e) => eventText(e).toLowerCase().includes(needle));
      if (!match)
        continue;
      hit = excerpt(eventText(match), needle);
    }
    out.push({
      id,
      events: ordered.length,
      lastMs: ordered.reduce((max, e) => Math.max(max, e.ts ?? 0), 0),
      lastIso: ordered[ordered.length - 1]?.iso ?? "",
      firstUser: firstUserText(ordered),
      hit
    });
  }
  return out.sort((a, b) => b.lastMs - a.lastMs);
}
function sessionTranscript(events, sessionId) {
  const out = [];
  const ordered = events.filter((e) => e.session === sessionId).sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0));
  for (const event of ordered) {
    if ((event.type === "user" || event.type === "assistant") && event.content) {
      out.push({ role: event.type === "user" ? "user" : "assistant", content: event.content });
    }
  }
  return out;
}
function sessionCursor(events, sessionId) {
  const cursor = { seq: 0, turn: 0 };
  for (const event of events) {
    if (event.session !== sessionId)
      continue;
    cursor.seq = Math.max(cursor.seq, event.seq ?? 0);
    cursor.turn = Math.max(cursor.turn, event.turn ?? 0);
  }
  return cursor;
}
function excerpt(text, needle, width = 90) {
  const flat = text.replace(/\s+/g, " ").trim();
  if (!flat)
    return "";
  const at = flat.toLowerCase().indexOf(needle.toLowerCase());
  if (at < 0)
    return flat.slice(0, width) + (flat.length > width ? "\u2026" : "");
  const half = Math.floor(width / 2);
  const start = Math.max(0, at - half);
  const end = Math.min(flat.length, at + needle.length + half);
  return (start ? "\u2026" : "") + flat.slice(start, end) + (end < flat.length ? "\u2026" : "");
}
function eventText(event) {
  return [event.content, event.reasoning, event.args, event.tool].filter((value) => typeof value === "string" && value.length > 0).join("\n");
}
function firstUserText(ordered) {
  const first = ordered.find((e) => e.type === "user");
  return (first?.content ?? "").replace(/\s+/g, " ").trim();
}

// search.ts
var WEB_SEARCH_TOOL_NAME = "web_search";
var TAVILY_URL = "https://api.tavily.com/search";
function nativeSearchFor(providerId, maxResults) {
  const count = clampResults(maxResults);
  switch (providerId) {
    case "glm":
    case "zai":
      return {
        tools: [
          {
            type: "web_search",
            web_search: {
              enable: "True",
              search_engine: "search_pro",
              search_result: "True",
              count: String(count)
            }
          }
        ]
      };
    case "kimi":
      return {
        tools: [{ type: "builtin_function", function: { name: "$web_search" } }],
        passthrough: ["$web_search"]
      };
    case "qwen":
      return { extraBody: { enable_search: true } };
    case "openrouter":
      return { extraBody: { plugins: [{ id: "web" }] } };
    case "ark":
      return null;
    default:
      return null;
  }
}
function resolveSearch(s) {
  if (s.mode === "off")
    return { native: null, tool: false, reason: "off" };
  const native = s.mode === "tool" ? null : nativeSearchFor(s.providerId, s.maxResults);
  const hasKey = s.apiKey.trim().length > 0;
  if (s.mode === "native")
    return native ? { native, tool: false } : { native: null, tool: false, reason: "provider-unsupported" };
  if (s.mode === "tool")
    return hasKey ? { native: null, tool: true } : { native: null, tool: false, reason: "no-key" };
  if (native)
    return { native, tool: false };
  return hasKey ? { native: null, tool: true } : { native: null, tool: false, reason: "no-key" };
}
function buildWebSearchToolDef() {
  return {
    name: WEB_SEARCH_TOOL_NAME,
    description: "Search the live web for current information (news, releases, prices, anything after the model knowledge cut-off) or facts that are not in the vault. Returns titles, URLs and excerpts \u2014 cite the URLs you used.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search query, as specific as possible" },
        max_results: { type: "integer", description: "How many results to return (1-20)" }
      },
      required: ["query"]
    }
  };
}
function buildTavilyBody(query, s, overrideResults) {
  return {
    query: query.trim().slice(0, 400),
    search_depth: s.depth,
    max_results: clampResults(overrideResults ?? s.maxResults),
    // The model reasons over the excerpts itself; a pre-chewed answer only
    // costs tokens and hides the sources.
    include_answer: false
  };
}
function formatTavilyResults(parsed) {
  const data = asRecord2(parsed);
  if (!data)
    return { ok: false, content: "web search failed: unparsable response" };
  const error = errorMessage(data);
  if (error)
    return { ok: false, content: `web search failed: ${error}` };
  const results = Array.isArray(data.results) ? data.results : [];
  if (!results.length)
    return { ok: true, content: "(no results)" };
  const blocks = results.map((raw, i) => {
    const item = asRecord2(raw) ?? {};
    const title = asString(item.title) || "(untitled)";
    const link = asString(item.url);
    const excerpt2 = oneLine(asString(item.content)).slice(0, 600);
    return [`${i + 1}. ${title}`, link ? `   ${link}` : "", excerpt2 ? `   ${excerpt2}` : ""].filter(Boolean).join("\n");
  });
  const answer = oneLine(asString(data.answer));
  return { ok: true, content: (answer ? `answer: ${answer}

` : "") + blocks.join("\n") };
}
function createWebSearchExecutor(post, getSettings) {
  return {
    async execute(name, argsJson) {
      if (name !== WEB_SEARCH_TOOL_NAME)
        return { ok: false, content: `unknown tool: ${name}` };
      const settings = getSettings();
      const apiKey = settings.apiKey.trim();
      if (!apiKey)
        return { ok: false, content: "web search is not configured: add a Tavily API key in the plugin settings" };
      let args;
      try {
        args = asRecord2(JSON.parse(argsJson || "{}")) ?? {};
      } catch {
        return { ok: false, content: "invalid JSON arguments" };
      }
      const query = asString(args.query).trim();
      if (!query)
        return { ok: false, content: "web search needs a non-empty query" };
      const override = typeof args.max_results === "number" ? args.max_results : void 0;
      try {
        const res = await post(
          TAVILY_URL,
          { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
          JSON.stringify(buildTavilyBody(query, settings, override))
        );
        if (res.status >= 400) {
          return { ok: false, content: `web search failed: HTTP ${res.status}: ${truncate(res.body, 300)}` };
        }
        let parsed;
        try {
          parsed = JSON.parse(res.body);
        } catch {
          return { ok: false, content: "web search failed: non-JSON response" };
        }
        return formatTavilyResults(parsed);
      } catch (e) {
        return { ok: false, content: "web search failed: " + (e instanceof Error ? e.message : String(e)) };
      }
    }
  };
}
function clampResults(n) {
  if (!Number.isFinite(n))
    return 5;
  return Math.min(20, Math.max(1, Math.round(n)));
}
function asRecord2(value) {
  return value !== null && typeof value === "object" ? value : null;
}
function asString(value) {
  return typeof value === "string" ? value : "";
}
function oneLine(text) {
  return text.replace(/\s+/g, " ").trim();
}
function withTimeout(promise, ms, label) {
  return new Promise((resolve, reject) => {
    const handle = window.setTimeout(() => reject(new Error(`${label} timed out after ${Math.round(ms / 1e3)}s`)), ms);
    promise.then(
      (value) => {
        window.clearTimeout(handle);
        resolve(value);
      },
      (reason) => {
        window.clearTimeout(handle);
        reject(reason instanceof Error ? reason : new Error(String(reason)));
      }
    );
  });
}
function errorMessage(data) {
  if (typeof data.error === "string")
    return data.error;
  const detail = asRecord2(data.detail);
  if (detail && typeof detail.error === "string")
    return detail.error;
  return "";
}

// i18n.ts
var zh = {
  viewName: "Vault Agent",
  viewIcon: "bot-message-square",
  newChat: "\u65B0\u5BF9\u8BDD",
  stop: "\u505C\u6B62",
  send: "\u53D1\u9001",
  inputPlaceholder: "\u5411\u667A\u80FD\u4F53\u63D0\u95EE\uFF0C\u6216\u8BA9\u5B83\u64CD\u4F5C\u4F60\u7684\u7B14\u8BB0\u2026\uFF08Enter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C\uFF09",
  welcome: "\u6211\u662F\u4F60\u7684 vault \u667A\u80FD\u4F53\u3002\u53EF\u4EE5\u76F4\u63A5\u95EE\u6211\u95EE\u9898\uFF0C\u4E5F\u53EF\u4EE5\u8BA9\u6211**\u641C\u7D22\u3001\u521B\u5EFA\u3001\u4FEE\u6539**\u7B14\u8BB0\u3002\n\n\u5F00\u59CB\u524D\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u586B\u5165\u6A21\u578B\u670D\u52A1\u5546\u7684 API Key\uFF08\u652F\u6301 DeepSeek / \u667A\u8C31 GLM / Kimi / \u901A\u4E49 Qwen / \u706B\u5C71\u65B9\u821F / \u817E\u8BAF\u6DF7\u5143 / Hermes(Nous) / OpenRouter \u6216\u4EFB\u610F OpenAI \u517C\u5BB9\u7AEF\u70B9\uFF09\u3002",
  needApiKey: "\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 API Key\u3002",
  noActiveNote: "\uFF08\u65E0\u6D3B\u52A8\u7B14\u8BB0\uFF09",
  toolCall: "\u5DE5\u5177\u8C03\u7528",
  toolResult: "\u7ED3\u679C",
  thinking: "\u601D\u8003\u4E2D\u2026",
  thought: "\u{1F4AD} \u601D\u8003\u8FC7\u7A0B",
  streaming: "\u751F\u6210\u4E2D\u2026",
  errPrefix: "\u8BF7\u6C42\u5931\u8D25",
  maxIterReached: "\u5DF2\u8FBE\u5355\u8F6E\u5DE5\u5177\u8C03\u7528\u4E0A\u9650\uFF0C\u8BF7\u7EE7\u7EED\u5BF9\u8BDD\u8BA9\u5B83\u63A5\u7740\u505A\u3002",
  settingsHeading: "Vault Agent",
  provider: "\u6A21\u578B\u670D\u52A1\u5546",
  providerDesc: "\u9009\u62E9\u670D\u52A1\u5546\u540E\u81EA\u52A8\u586B\u5145 API \u5730\u5740\uFF0C\u53EF\u518D\u624B\u52A8\u4FEE\u6539\u3002Trae \u540C\u6E90\uFF08\u706B\u5C71\u65B9\u821F\uFF09\u3001Qoder \u540C\u6E90\uFF08\u901A\u4E49\uFF09\u3001WorkBuddy \u540C\u6E90\uFF08\u817E\u8BAF\u6DF7\u5143\uFF09\u7B49\u5747\u53EF\u76F4\u8FDE\u3002",
  baseUrl: "API \u5730\u5740 (Base URL)",
  apiKey: "API Key",
  apiKeyDesc: "\u4EC5\u4FDD\u5B58\u5728\u672C\u673A Obsidian \u914D\u7F6E\u5185\uFF0C\u4E0D\u4F1A\u4E0A\u4F20\u3002",
  proxy: "\u672C\u5730\u4EE3\u7406\uFF08\u53EF\u9009\uFF09",
  proxyDesc: "\u586B HTTP \u4EE3\u7406\u5730\u5740\uFF08\u5982 http://127.0.0.1:9000\uFF09\uFF0CAI \u8BF7\u6C42\u7ECF\u5B83\u8F6C\u53D1\uFF1B\u7559\u7A7A\u76F4\u8FDE\u3002\u4EC5\u684C\u9762\u7AEF\u751F\u6548\u3002",
  model: "\u6A21\u578B ID",
  modelDesc: "\u4EE5\u670D\u52A1\u5546\u63A7\u5236\u53F0\u4E3A\u51C6\uFF0C\u53EF\u81EA\u7531\u586B\u5199\u3002",
  modelPreset: "\u5E38\u7528\u6A21\u578B\uFF08\u70B9\u9009\u586B\u5165\uFF09",
  temperature: "Temperature",
  maxTokens: "\u5355\u6B21\u56DE\u590D\u6700\u5927 Tokens",
  maxIterations: "\u5355\u8F6E\u6700\u5927\u5DE5\u5177\u8C03\u7528\u6B21\u6570",
  autoContext: "\u81EA\u52A8\u9644\u5E26\u5F53\u524D\u7B14\u8BB0\u8DEF\u5F84",
  autoContextDesc: "\u5728\u7CFB\u7EDF\u63D0\u793A\u4E2D\u544A\u77E5\u667A\u80FD\u4F53\u5F53\u524D\u6B63\u5728\u7F16\u8F91\u7684\u7B14\u8BB0\uFF0C\u4FBF\u4E8E\u76F4\u63A5\u64CD\u4F5C\u3002",
  autoApprove: "\u81EA\u52A8\u6267\u884C\u5199\u64CD\u4F5C",
  autoApproveDesc: "\u5173\u95ED\u540E\uFF0C\u6BCF\u6B21\u521B\u5EFA/\u4FEE\u6539\u7B14\u8BB0\u524D\u4F1A\u5148\u8BF7\u6C42\u786E\u8BA4\u3002",
  systemPrompt: "\u7CFB\u7EDF\u63D0\u793A\u8BCD",
  systemPromptDesc: "\u7559\u7A7A\u4F7F\u7528\u5185\u7F6E\u9ED8\u8BA4\uFF08\u4E2D\u6587\uFF09\u3002",
  language: "\u754C\u9762\u8BED\u8A00",
  languageDesc: "\u63D2\u4EF6\u754C\u9762\u4E0E\u9ED8\u8BA4\u7CFB\u7EDF\u63D0\u793A\u8BED\u8A00\u3002",
  confirmTitle: "\u667A\u80FD\u4F53\u8BF7\u6C42\u5199\u64CD\u4F5C",
  confirmAllow: "\u5141\u8BB8",
  confirmDeny: "\u62D2\u7EDD",
  denied: "\u7528\u6237\u62D2\u7EDD\u4E86\u8BE5\u64CD\u4F5C\u3002",
  openSettings: "\u6253\u5F00\u8BBE\u7F6E",
  clearChat: "\u6E05\u7A7A\u5F53\u524D\u5BF9\u8BDD",
  emptySearch: "\u6CA1\u6709\u5339\u914D\u7ED3\u679C",
  history: "\u5386\u53F2\u8BB0\u5F55",
  historyFilter: "\u641C\u7D22\u5386\u53F2\u5BF9\u8BDD\u2026",
  historyEmpty: "\u8FD8\u6CA1\u6709\u5386\u53F2\u8BB0\u5F55\uFF0C\u53D1\u4E00\u6761\u6D88\u606F\u540E\u5C31\u4F1A\u51FA\u73B0\u5728\u8FD9\u91CC\u3002",
  historyNoUser: "\uFF08\u65E0\u7528\u6237\u6D88\u606F\uFF09",
  historyEvents: "\u6761\u4E8B\u4EF6",
  backToChat: "\u8FD4\u56DE\u5BF9\u8BDD",
  historyLoaded: "\u5DF2\u8F7D\u5165\u4F1A\u8BDD",
  searchMode: "\u8054\u7F51\u641C\u7D22",
  searchModeDesc: "\u8BA9\u6A21\u578B\u62FF\u5230\u8BAD\u7EC3\u6570\u636E\u4E4B\u540E\u7684\u4FE1\u606F\u3002\u670D\u52A1\u5546\u5185\u7F6E\u8054\u7F51\u4E0E\u63D2\u4EF6\u641C\u7D22\u5DE5\u5177\u4E8C\u9009\u4E00\uFF08\u81EA\u52A8\u6A21\u5F0F\u4F18\u5148\u7528\u5185\u7F6E\uFF09\u3002",
  searchModeOff: "\u5173\u95ED",
  searchModeAuto: "\u81EA\u52A8\uFF08\u4F18\u5148\u670D\u52A1\u5546\u5185\u7F6E\uFF09",
  searchModeNative: "\u4EC5\u670D\u52A1\u5546\u5185\u7F6E",
  searchModeTool: "\u4EC5\u63D2\u4EF6\u5DE5\u5177\uFF08Tavily\uFF09",
  searchApiKey: "Tavily API Key",
  searchApiKeyDesc: "\u4EC5\u4FDD\u5B58\u5728\u672C\u673A Obsidian \u914D\u7F6E\u5185\u3002\u5230 app.tavily.com \u6CE8\u518C\u540E\u590D\u5236 Key\uFF0C\u514D\u8D39\u989D\u5EA6 1000 \u6B21/\u6708\u3002",
  searchMaxResults: "\u6BCF\u6B21\u641C\u7D22\u8FD4\u56DE\u6761\u6570",
  searchDepth: "\u641C\u7D22\u6DF1\u5EA6",
  searchDepthBasic: "basic\uFF08\u5FEB\uFF0C1 credit\uFF09",
  searchDepthAdvanced: "advanced\uFF08\u66F4\u5168\uFF0C2 credits\uFF09",
  searchUnsupported: "\u5F53\u524D\u670D\u52A1\u5546\u4E0D\u63D0\u4F9B\u5185\u7F6E\u8054\u7F51\u3002\u6539\u7528\u300C\u4EC5\u63D2\u4EF6\u5DE5\u5177\u300D\u5E76\u586B Tavily Key\uFF0C\u6216\u6362\u7528 GLM / Kimi / Qwen / OpenRouter\u3002",
  searchFallback: "\u670D\u52A1\u5546\u62D2\u7EDD\u4E86\u8054\u7F51\u53C2\u6570\uFF0C\u672C\u8F6E\u5DF2\u6309\u4E0D\u8054\u7F51\u91CD\u8BD5\u3002",
  busy: "\u667A\u80FD\u4F53\u8FD8\u5728\u56DE\u590D\u4E2D\uFF0C\u5B8C\u6210\u540E\u518D\u6253\u5F00\u5386\u53F2\u8BB0\u5F55\u3002",
  maxIterNoAnswer: "\u26A0\uFE0F \u5DF2\u8FBE\u5355\u8F6E\u5DE5\u5177\u8C03\u7528\u4E0A\u9650\uFF0C\u672C\u8F6E\u6CA1\u6709\u751F\u6210\u56DE\u7B54\u3002\u56DE\u590D\u300C\u7EE7\u7EED\u300D\u6211\u5C31\u63A5\u7740\u505A\uFF1B\u4E5F\u53EF\u4EE5\u5728\u8BBE\u7F6E\u91CC\u8C03\u5927\u300C\u5355\u8F6E\u6700\u5927\u5DE5\u5177\u8C03\u7528\u6B21\u6570\u300D\u3002",
  emptyReply: "\u26A0\uFE0F \u6A21\u578B\u672C\u8F6E\u6CA1\u6709\u8FD4\u56DE\u4EFB\u4F55\u5185\u5BB9\uFF08\u53EF\u80FD\u662F\u670D\u52A1\u5546\u4FA7\u4E2D\u65AD\u3001\u6216\u89E6\u53D1\u4E86\u8F93\u51FA\u957F\u5EA6\u9650\u5236\uFF09\u3002\u8BF7\u76F4\u63A5\u91CD\u8BD5\uFF0C\u6216\u6362\u4E2A\u8BF4\u6CD5\u518D\u95EE\u4E00\u6B21\u3002"
};
var en = {
  viewName: "Vault Agent",
  viewIcon: "bot-message-square",
  newChat: "New chat",
  stop: "Stop",
  send: "Send",
  inputPlaceholder: "Ask the agent, or have it work on your notes\u2026 (Enter to send, Shift+Enter for newline)",
  welcome: "I'm your vault agent. Ask me anything, or have me **search, create, and edit** notes.\n\nPick a provider and paste an API key in settings (DeepSeek / GLM / Kimi / Qwen / Volcengine Ark / Tencent Hunyuan / Hermes(Nous) / OpenRouter / any OpenAI-compatible endpoint).",
  needApiKey: "Please set an API key in settings first.",
  noActiveNote: "(no active note)",
  toolCall: "Tool call",
  toolResult: "Result",
  thinking: "Thinking\u2026",
  thought: "\u{1F4AD} Thought process",
  streaming: "Generating\u2026",
  errPrefix: "Request failed",
  maxIterReached: "Tool-call limit for this turn reached \u2014 keep chatting to continue.",
  settingsHeading: "Vault Agent",
  provider: "Provider",
  providerDesc: "Base URL is auto-filled when you pick a provider; adjust freely. Volcengine Ark (Trae), DashScope (Qoder), Tencent Hunyuan (WorkBuddy) connect directly.",
  baseUrl: "API base URL",
  apiKey: "API key",
  apiKeyDesc: "Stored locally in Obsidian config only; never uploaded.",
  proxy: "Local proxy (optional)",
  proxyDesc: "HTTP proxy for AI requests (e.g. http://127.0.0.1:9000). Leave empty for direct connection. Desktop only.",
  model: "Model ID",
  modelDesc: "Use the model ID from your provider console.",
  modelPreset: "Common models (click to fill)",
  temperature: "Temperature",
  maxTokens: "Max tokens per reply",
  maxIterations: "Max tool calls per turn",
  autoContext: "Include active note path",
  autoContextDesc: "Tells the agent which note you are editing, so it can act on it directly.",
  autoApprove: "Auto-approve write actions",
  autoApproveDesc: "When off, every create/edit asks for confirmation first.",
  systemPrompt: "System prompt",
  systemPromptDesc: "Leave empty to use the built-in default (Chinese).",
  language: "UI language",
  languageDesc: "Language of the plugin UI and default system prompt.",
  confirmTitle: "Agent requests a write action",
  confirmAllow: "Allow",
  confirmDeny: "Deny",
  denied: "User denied this action.",
  openSettings: "Open settings",
  clearChat: "Clear conversation",
  emptySearch: "No matches",
  history: "History",
  historyFilter: "Search history\u2026",
  historyEmpty: "No history yet \u2014 send a message and it will show up here.",
  historyNoUser: "(no user message)",
  historyEvents: "events",
  backToChat: "Back to chat",
  historyLoaded: "Loaded session",
  searchMode: "Web search",
  searchModeDesc: "Give the model information past its training cut-off. Provider-native search and the plugin tool are alternatives (auto prefers native).",
  searchModeOff: "Off",
  searchModeAuto: "Auto (prefer provider-native)",
  searchModeNative: "Provider-native only",
  searchModeTool: "Plugin tool only (Tavily)",
  searchApiKey: "Tavily API key",
  searchApiKeyDesc: "Stored locally in Obsidian config only. Get a key at app.tavily.com \u2014 the free tier covers 1,000 searches/month.",
  searchMaxResults: "Results per search",
  searchDepth: "Search depth",
  searchDepthBasic: "basic (fast, 1 credit)",
  searchDepthAdvanced: "advanced (thorough, 2 credits)",
  searchUnsupported: 'This provider has no native web search. Switch to "Plugin tool only" and add a Tavily key, or move to GLM / Kimi / Qwen / OpenRouter.',
  searchFallback: "The provider rejected the search parameters; this turn was retried without web search.",
  busy: "The agent is still replying \u2014 open history again once it finishes.",
  maxIterNoAnswer: '\u26A0\uFE0F Hit the tool-call limit for this turn, so no answer was generated. Reply "continue" and I will pick it up, or raise "Max tool calls per turn" in settings.',
  emptyReply: "\u26A0\uFE0F The model returned no content this turn (a provider-side interruption, or the output-length limit). Try again, or rephrase the question."
};
var STRINGS = { zh, en };
function t(lang, key) {
  return STRINGS[lang][key];
}

// tools.ts
var import_obsidian = require("obsidian");
var MAX_READ = 3e4;
var MAX_RESULTS = 60;
function buildToolDefs() {
  return [
    {
      name: "list_notes",
      description: "List note files in a folder of the vault (recursive).",
      parameters: {
        type: "object",
        properties: {
          folder: { type: "string", description: 'Folder path relative to vault root, "." for whole vault' },
          glob: { type: "string", description: 'Optional filename substring filter, e.g. "meeting"' }
        },
        required: ["folder"]
      }
    },
    {
      name: "read_note",
      description: "Read the full text of a note by path.",
      parameters: {
        type: "object",
        properties: { path: { type: "string", description: 'Vault-relative path, e.g. "Daily/2026-09-13.md"' } },
        required: ["path"]
      }
    },
    {
      name: "search_notes",
      description: "Search note contents with a literal or regex pattern. Returns file, line number and context.",
      parameters: {
        type: "object",
        properties: {
          pattern: { type: "string", description: "Text or regular expression" },
          regex: { type: "boolean", description: "Treat pattern as a regular expression (default false)" },
          folder: { type: "string", description: "Optional folder to limit the search" }
        },
        required: ["pattern"]
      }
    },
    {
      name: "get_active_note",
      description: "Get the path and content of the note currently open in the editor.",
      parameters: { type: "object", properties: {} }
    },
    {
      name: "create_note",
      description: "Create a new note (or overwrite an existing one when overwrite=true). Parent folders are created automatically.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Vault-relative path ending in .md" },
          content: { type: "string", description: "Full markdown content of the note" },
          overwrite: { type: "boolean", description: "Overwrite if the file exists (default false)" }
        },
        required: ["path", "content"]
      }
    },
    {
      name: "edit_note",
      description: "Replace an exact string inside an existing note. old_string must match exactly and uniquely; for non-unique matches include more surrounding lines.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Vault-relative path" },
          old_string: { type: "string", description: "Exact existing text to replace" },
          new_string: { type: "string", description: "Replacement text" },
          replace_all: { type: "boolean", description: "Replace every occurrence (default false)" }
        },
        required: ["path", "old_string", "new_string"]
      }
    },
    {
      name: "append_note",
      description: "Append text to the end of an existing note (creates a leading blank line when needed).",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Vault-relative path" },
          content: { type: "string", description: "Text to append" }
        },
        required: ["path", "content"]
      }
    },
    {
      name: "read_properties",
      description: "Read frontmatter/properties and basic stats of a note.",
      parameters: {
        type: "object",
        properties: { path: { type: "string", description: "Vault-relative path" } },
        required: ["path"]
      }
    }
  ];
}
var VaultToolExecutor = class {
  constructor(app, getActivePath) {
    this.app = app;
    this.getActivePath = getActivePath;
  }
  async execute(name, argsJson) {
    let parsed = {};
    try {
      parsed = JSON.parse(argsJson || "{}");
    } catch {
      return { ok: false, content: "invalid JSON arguments" };
    }
    const args = parsed !== null && typeof parsed === "object" ? parsed : {};
    const s = (key, fallback = "") => {
      const v = args[key];
      switch (typeof v) {
        case "string":
          return v;
        case "number":
        case "bigint":
        case "boolean":
          return String(v);
        case "object":
          return v !== null ? JSON.stringify(v) : fallback;
        default:
          return fallback;
      }
    };
    const b = (key) => args[key] === true;
    try {
      switch (name) {
        case "list_notes":
          return ok(await this.listNotes(s("folder", "."), args.glob === void 0 ? void 0 : s("glob")));
        case "read_note":
          return ok(await this.readNote(s("path")));
        case "search_notes":
          return ok(await this.searchNotes(s("pattern"), b("regex"), args.folder === void 0 ? void 0 : s("folder")));
        case "get_active_note":
          return ok(await this.activeNote());
        case "create_note":
          return ok(await this.createNote(s("path"), s("content"), b("overwrite")));
        case "edit_note":
          return ok(await this.editNote(s("path"), s("old_string"), s("new_string"), b("replace_all")));
        case "append_note":
          return ok(await this.appendNote(s("path"), s("content")));
        case "read_properties":
          return ok(await this.readProperties(s("path")));
        default:
          return { ok: false, content: `unknown tool: ${name}` };
      }
    } catch (e) {
      return { ok: false, content: "error: " + (e instanceof Error ? e.message : String(e)) };
    }
  }
  resolve(path) {
    return (0, import_obsidian.normalizePath)(String(path ?? "").trim().replace(/^\/+/, ""));
  }
  async listNotes(folder, glob) {
    const fp = this.resolve(folder);
    const af = this.app.vault.getAbstractFileByPath(fp);
    let files;
    if (af instanceof import_obsidian.TFolder) {
      files = this.app.vault.getMarkdownFiles().filter((f) => f.path === fp || f.path.startsWith(fp === "/" ? "" : fp + "/"));
    } else if (af instanceof import_obsidian.TFile) {
      files = [af];
    } else {
      files = this.app.vault.getMarkdownFiles();
    }
    if (glob)
      files = files.filter((f) => f.name.toLowerCase().includes(String(glob).toLowerCase()));
    files = files.slice(0, 500);
    if (!files.length)
      return "(no notes found)";
    return files.map((f) => `${f.path} (${f.stat.size}B)`).join("\n");
  }
  async readNote(path) {
    const file = this.mustFile(path);
    const text = await this.app.vault.cachedRead(file);
    if (text.length > MAX_READ) {
      return truncate(text, MAX_READ) + `
[note truncated; ${text.length} chars total \u2014 use search_notes or ask for a section]`;
    }
    return text || "(empty note)";
  }
  async searchNotes(pattern, regex, folder) {
    if (!pattern)
      return "empty pattern";
    let re;
    try {
      re = regex ? new RegExp(pattern, "gi") : new RegExp(pattern.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi");
    } catch (e) {
      return "invalid regex: " + (e instanceof Error ? e.message : String(e));
    }
    const fp = folder ? this.resolve(folder) : null;
    const files = this.app.vault.getMarkdownFiles().filter((f) => !fp || f.path === fp || f.path.startsWith(fp + "/"));
    const out = [];
    let hits = 0;
    for (const file of files) {
      if (hits >= MAX_RESULTS)
        break;
      const text = await this.app.vault.cachedRead(file);
      const lines = text.split("\n");
      for (let i = 0; i < lines.length && hits < MAX_RESULTS; i++) {
        re.lastIndex = 0;
        if (re.test(lines[i])) {
          out.push(`${file.path}:${i + 1}: ${lines[i].trim().slice(0, 200)}`);
          hits++;
        }
      }
    }
    return out.length ? out.join("\n") : "(no matches)";
  }
  async activeNote() {
    const path = this.getActivePath();
    if (!path)
      return "(no active note)";
    const file = this.app.vault.getFileByPath(path);
    if (!file)
      return `(active file not readable: ${path})`;
    const text = await this.app.vault.cachedRead(file);
    return `path: ${file.path}
---
` + truncate(text, MAX_READ);
  }
  async ensureFolder(path) {
    const idx = path.lastIndexOf("/");
    if (idx <= 0)
      return;
    const dir = this.resolve(path.slice(0, idx));
    if (!dir || this.app.vault.getAbstractFileByPath(dir))
      return;
    await this.ensureFolder(dir + "/x");
    if (!this.app.vault.getAbstractFileByPath(dir))
      await this.app.vault.createFolder(dir);
  }
  async createNote(path, content, overwrite) {
    const p = this.resolve(path);
    if (!p)
      return "missing path";
    if (!/\.(md|canvas)$/i.test(p))
      return "path must end with .md";
    const existing = this.app.vault.getFileByPath(p);
    if (existing) {
      if (!overwrite)
        return `file already exists: ${p}. Set overwrite=true to replace it, or use edit_note/append_note.`;
      await this.app.vault.modify(existing, content);
      return `overwrote ${p} (${content.length} chars)`;
    }
    await this.ensureFolder(p);
    await this.app.vault.create(p, content);
    return `created ${p} (${content.length} chars)`;
  }
  async editNote(path, oldString, newString, replaceAll) {
    const file = this.mustFile(path);
    const text = await this.app.vault.read(file);
    const count = text.split(oldString).length - 1;
    if (count === 0) {
      return `old_string not found in ${file.path}. Read the note again and copy the exact text (including whitespace).`;
    }
    if (count > 1 && !replaceAll) {
      return `old_string appears ${count} times in ${file.path}. Provide more surrounding lines to make it unique, or set replace_all=true.`;
    }
    const updated = replaceAll ? text.split(oldString).join(newString) : text.replace(oldString, newString);
    await this.app.vault.modify(file, updated);
    return `edited ${file.path} (${count} occurrence${count > 1 ? "s" : ""} replaced)`;
  }
  async appendNote(path, content) {
    const file = this.mustFile(path);
    const text = await this.app.vault.read(file);
    const glue = text.length && !text.endsWith("\n") ? "\n" : "";
    await this.app.vault.modify(file, text + glue + "\n" + content);
    return `appended ${content.length} chars to ${file.path}`;
  }
  async readProperties(path) {
    const file = this.mustFile(path);
    const cache = this.app.metadataCache.getFileCache(file);
    const fm = cache?.frontmatter ?? {};
    const lines = [
      `path: ${file.path}`,
      `size: ${file.stat.size}B`,
      `tags: ${(cache?.tags ?? []).map((t2) => t2.tag).join(", ") || "(none)"}`,
      `frontmatter: ${JSON.stringify(fm)}`
    ];
    return lines.join("\n");
  }
  mustFile(path) {
    const p = this.resolve(path);
    const file = this.app.vault.getFileByPath(p);
    if (!file)
      throw new Error(`note not found: ${p}`);
    if (!(file instanceof import_obsidian.TFile))
      throw new Error(`not a file: ${p}`);
    return file;
  }
};
function ok(content) {
  return { ok: true, content };
}

// view.ts
var VIEW_TYPE_AGENT = "vault-agent-view";
var AgentView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.messages = [];
    this.running = false;
    this.abort = null;
    /** Raw history.jsonl, cached while the history panel is open. */
    this.historyText = "";
    this.historyQuery = "";
  }
  getViewType() {
    return VIEW_TYPE_AGENT;
  }
  getDisplayText() {
    return t(this.plugin.settings.lang, "viewName");
  }
  getIcon() {
    return t(this.plugin.settings.lang, "viewIcon");
  }
  async onOpen() {
    this.messages = this.plugin.loadHistory();
    if (!this.messages.length) {
      this.plugin.startSession();
    } else {
      const sessionId = this.plugin.settings.sessionId;
      if (sessionId) {
        const cursor = sessionCursor(parseHistory(await this.plugin.readHistoryText()), sessionId);
        this.plugin.resumeSession(sessionId, cursor);
      }
    }
    this.renderShell();
    if (!this.messages.length)
      this.addWelcome();
    else
      this.renderAllHistory();
  }
  async onClose() {
    await this.plugin.saveHistory(this.messages);
    await this.plugin.history.flush();
    this.abort?.abort();
  }
  st(key) {
    return t(this.plugin.settings.lang, key);
  }
  renderShell() {
    const root = this.contentEl;
    root.empty();
    root.addClass("va-root");
    const header = root.createDiv({ cls: "va-header" });
    const brand = header.createDiv({ cls: "va-brand" });
    (0, import_obsidian2.setIcon)(brand, "bot-message-square");
    brand.createSpan({ text: this.st("viewName") + " \xB7 " + this.plugin.currentModelLabel() });
    const actions = header.createDiv({ cls: "va-header-actions" });
    const historyBtn = actions.createEl("button", { cls: "va-icon-btn", attr: { "aria-label": this.st("history") } });
    (0, import_obsidian2.setIcon)(historyBtn, "history");
    historyBtn.addEventListener("click", () => void this.openHistory());
    const newBtn = actions.createEl("button", { cls: "va-icon-btn", attr: { "aria-label": this.st("newChat") } });
    (0, import_obsidian2.setIcon)(newBtn, "plus");
    newBtn.addEventListener("click", () => {
      if (this.running)
        return;
      this.plugin.startSession();
      this.messages = [];
      void this.plugin.saveHistory([]);
      this.renderShell();
      this.addWelcome();
    });
    const clearBtn = actions.createEl("button", { cls: "va-icon-btn", attr: { "aria-label": this.st("clearChat") } });
    (0, import_obsidian2.setIcon)(clearBtn, "trash-2");
    clearBtn.addEventListener("click", () => {
      if (this.running)
        return;
      this.plugin.startSession();
      this.messages = [];
      void this.plugin.saveHistory([]);
      this.renderShell();
      this.addWelcome();
    });
    const settingsBtn = actions.createEl("button", { cls: "va-icon-btn", attr: { "aria-label": this.st("openSettings") } });
    (0, import_obsidian2.setIcon)(settingsBtn, "settings");
    settingsBtn.addEventListener("click", () => this.plugin.openSettings());
    this.msgsEl = root.createDiv({ cls: "va-messages" });
    this.historyEl = root.createDiv({ cls: "va-history" });
    this.historyEl.hide();
    this.inputAreaEl = root.createDiv({ cls: "va-input-area" });
    const ta = this.inputAreaEl.createEl("textarea", { cls: "va-input", attr: { placeholder: this.st("inputPlaceholder"), rows: "3" } });
    this.inputEl = ta;
    const btnRow = this.inputAreaEl.createDiv({ cls: "va-send-row" });
    this.stopBtn = btnRow.createEl("button", { cls: "va-stop-btn", text: "\u23F9 " + this.st("stop") });
    this.stopBtn.disabled = true;
    this.stopBtn.addEventListener("click", () => this.abort?.abort());
    this.sendBtn = btnRow.createEl("button", { cls: "va-send-btn mod-cta", text: "\u27A4 " + this.st("send") });
    this.sendBtn.addEventListener("click", () => void this.send());
    ta.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey && !e.isComposing) {
        e.preventDefault();
        void this.send();
      }
    });
  }
  addWelcome() {
    const el = this.msgsEl.createDiv({ cls: "va-welcome" });
    this.renderMarkdown(el, this.st("welcome"));
  }
  renderAllHistory() {
    for (const m of this.messages) {
      if (m.role === "user")
        this.renderUserBubble(m.content ?? "");
      else if (m.role === "assistant" && m.content)
        this.renderAssistantDone(m.content);
    }
    this.scrollBottom();
  }
  /** Chat and history share the view; the panel replaces the message list. */
  setMode(mode) {
    const onHistory = mode === "history";
    this.msgsEl.toggle(!onHistory);
    this.inputAreaEl.toggle(!onHistory);
    this.historyEl.toggle(onHistory);
  }
  async openHistory() {
    if (this.running) {
      new import_obsidian2.Notice(this.st("busy"));
      return;
    }
    this.historyText = await this.plugin.readHistoryText();
    this.historyQuery = "";
    this.setMode("history");
    this.renderHistory();
  }
  renderHistory() {
    this.historyEl.empty();
    const bar = this.historyEl.createDiv({ cls: "va-history-bar" });
    const back = bar.createEl("button", { cls: "va-icon-btn", attr: { "aria-label": this.st("backToChat") } });
    (0, import_obsidian2.setIcon)(back, "arrow-left");
    back.addEventListener("click", () => this.setMode("chat"));
    const filter = bar.createEl("input", {
      cls: "va-history-filter",
      attr: { type: "search", placeholder: this.st("historyFilter"), "aria-label": this.st("historyFilter") }
    });
    filter.value = this.historyQuery;
    const list = this.historyEl.createDiv({ cls: "va-history-list" });
    filter.addEventListener("input", () => {
      this.historyQuery = filter.value;
      this.renderHistoryList(list);
    });
    filter.addEventListener("keydown", (e) => {
      if (e.key === "Escape")
        this.setMode("chat");
    });
    this.renderHistoryList(list);
    filter.focus();
  }
  renderHistoryList(list) {
    list.empty();
    const events = parseHistory(this.historyText);
    if (!events.length) {
      list.createDiv({ cls: "va-history-empty", text: this.st("historyEmpty") });
      return;
    }
    const sessions = summarizeSessions(events, this.historyQuery);
    if (!sessions.length) {
      list.createDiv({ cls: "va-history-empty", text: this.st("emptySearch") });
      return;
    }
    for (const session of sessions) {
      const row = list.createDiv({ cls: "va-history-item" });
      const meta = row.createDiv({ cls: "va-history-meta" });
      meta.createSpan({ cls: "va-history-time", text: formatStamp(session.lastIso) });
      meta.createSpan({ cls: "va-history-count", text: `${session.events} ${this.st("historyEvents")}` });
      row.createDiv({ cls: "va-history-first", text: session.firstUser || this.st("historyNoUser") });
      if (session.hit)
        row.createDiv({ cls: "va-history-hit", text: session.hit });
      row.addEventListener("click", () => this.loadSession(events, session.id));
    }
  }
  /** Replace the chat with a past conversation; new turns keep appending to it. */
  loadSession(events, sessionId) {
    this.messages = sessionTranscript(events, sessionId).map((m) => ({ role: m.role, content: m.content }));
    this.plugin.resumeSession(sessionId, sessionCursor(events, sessionId));
    void this.plugin.saveHistory(this.messages);
    this.renderShell();
    if (this.messages.length)
      this.renderAllHistory();
    else
      this.addWelcome();
    new import_obsidian2.Notice(`${this.st("historyLoaded")}: ${sessionId.slice(0, 8)}`);
  }
  scrollBottom() {
    this.msgsEl.scrollTop = this.msgsEl.scrollHeight;
  }
  /**
   * Render markdown without the stray blank lines Obsidian's renderer produces
   * (empty <p> from leading/trailing newlines, <br> runs at block edges).
   */
  renderMarkdown(container, text) {
    void import_obsidian2.MarkdownRenderer.render(this.app, text.trim() || "\u2026", container, "", this).then(() => {
      container.querySelectorAll("br").forEach((br) => {
        const parent = br.parentElement;
        if (!parent)
          return;
        if (br.previousElementSibling === null || br.nextElementSibling === null || br.previousElementSibling?.tagName === "BR") {
          br.remove();
        }
      });
      container.querySelectorAll("p, li").forEach((p) => {
        if (!p.textContent?.trim() && !p.querySelector("img,video,a,code,pre,table,svg"))
          p.remove();
      });
      container.querySelectorAll("hr").forEach((hr) => {
        if (!hr.previousElementSibling || !hr.nextElementSibling || hr.previousElementSibling.tagName === "HR")
          hr.remove();
      });
    });
  }
  renderUserBubble(text) {
    const el = this.msgsEl.createDiv({ cls: "va-msg va-user" });
    el.createDiv({ cls: "va-user-text", text });
    this.scrollBottom();
    return el;
  }
  renderAssistantDone(text) {
    const el = this.msgsEl.createDiv({ cls: "va-msg va-assistant" });
    this.renderMarkdown(el, text);
    this.scrollBottom();
    return el;
  }
  /**
   * Streaming assistant bubble: reasoning (if the model streams it) goes into a
   * collapsible block that stays collapsed above the answer once done.
   */
  beginStreamingBubble() {
    const el = this.msgsEl.createDiv({ cls: "va-msg va-assistant va-streaming" });
    const textEl = el.createDiv({ cls: "va-stream-text" });
    let acc = "";
    let reasoningEl = null;
    let reasoningTextEl = null;
    let reasoningAcc = "";
    return {
      el,
      push: (delta) => {
        acc += delta;
        textEl.textContent = acc;
        this.scrollBottom();
      },
      pushReasoning: (delta) => {
        let d = reasoningEl;
        if (!d) {
          d = el.createEl("details", { cls: "va-reasoning" });
          d.setAttribute("open", "");
          d.createEl("summary", { text: this.st("thinking") });
          reasoningTextEl = d.createDiv({ cls: "va-reasoning-text" });
          el.insertBefore(d, textEl);
          reasoningEl = d;
        }
        reasoningAcc += delta;
        if (reasoningTextEl) {
          reasoningTextEl.textContent = normalizeReasoning(reasoningAcc);
          reasoningTextEl.scrollTop = reasoningTextEl.scrollHeight;
        }
        this.scrollBottom();
      },
      finish: (full, reasoning) => {
        el.removeClass("va-streaming");
        textEl.remove();
        const finalReasoning = normalizeReasoning(reasoning || reasoningAcc);
        if (finalReasoning) {
          if (!reasoningEl) {
            reasoningEl = el.createEl("details", { cls: "va-reasoning" });
            reasoningEl.createEl("summary", { text: this.st("thought") });
            reasoningTextEl = reasoningEl.createDiv({ cls: "va-reasoning-text" });
          }
          reasoningEl.removeAttribute("open");
          const summary = reasoningEl.querySelector("summary");
          if (summary)
            summary.textContent = this.st("thought");
          if (reasoningTextEl)
            reasoningTextEl.textContent = finalReasoning;
        } else if (reasoningEl) {
          reasoningEl.remove();
        }
        const done = el.createDiv({ cls: "va-assistant-body" });
        this.renderMarkdown(done, full || acc);
        this.scrollBottom();
      }
    };
  }
  addToolChip(call) {
    const chip = this.msgsEl.createDiv({ cls: "va-tool-chip" });
    const summary = chip.createDiv({ cls: "va-tool-summary" });
    const icon = summary.createSpan({ cls: "va-tool-icon" });
    (0, import_obsidian2.setIcon)(icon, "loader-2");
    icon.addClass("va-spinner");
    let argsPreview = "";
    try {
      const a = JSON.parse(call.function.arguments || "{}");
      if (a !== null && typeof a === "object") {
        argsPreview = Object.entries(a).map(([k, v]) => `${k}=${String(v).slice(0, 60)}`).join(" ");
      }
    } catch {
      argsPreview = call.function.arguments;
    }
    summary.createSpan({ text: `${call.function.name}  ${argsPreview.slice(0, 120)}` });
    const details = chip.createEl("details", { cls: "va-tool-details" });
    details.createEl("summary", { text: this.st("toolResult") });
    details.createEl("pre", { text: "\u2026" });
    this.scrollBottom();
    return chip;
  }
  /** Fill in the result of a tool call on its existing chip (single chip per call). */
  completeToolChip(chip, result) {
    if (!result.ok)
      chip.addClass("va-tool-error");
    const icon = chip.querySelector(".va-tool-icon");
    if (icon) {
      (0, import_obsidian2.setIcon)(icon, result.ok ? "check" : "x");
      icon.removeClass("va-spinner");
    }
    const pre = chip.querySelector(".va-tool-details pre");
    if (pre)
      pre.textContent = result.content.slice(0, 2e3);
  }
  buildSystemPrompt() {
    const s = this.plugin.settings;
    const active = this.app.workspace.getActiveFile();
    const zhMode = s.lang === "zh";
    const base = s.systemPrompt.trim() || (zhMode ? `\u4F60\u662F Obsidian \u5E93\uFF08vault\uFF09\u5185\u7684\u667A\u80FD\u4F53\u52A9\u624B\uFF0C\u53EF\u4EE5\u501F\u52A9\u5DE5\u5177\u8BFB\u5199\u548C\u68C0\u7D22\u7528\u6237\u7684\u7B14\u8BB0\u3002\u89C4\u5219\uFF1A
- \u6D89\u53CA\u7B14\u8BB0\u5185\u5BB9\u65F6\u4F18\u5148\u4F7F\u7528\u5DE5\u5177\uFF08search_notes/read_note/list_notes\uFF09\u83B7\u53D6\u771F\u5B9E\u5185\u5BB9\uFF0C\u4E0D\u8981\u51ED\u7A7A\u7F16\u9020\u7B14\u8BB0\u5185\u5BB9\u3002
- \u7F16\u8F91\u7B14\u8BB0\u7528 edit_note\uFF0Cold_string \u5FC5\u987B\u4E0E\u539F\u6587\u5B8C\u5168\u4E00\u81F4\u4E14\u552F\u4E00\uFF1B\u65B0\u5EFA\u7528 create_note\uFF1B\u8FFD\u52A0\u7528 append_note\u3002
- \u6240\u6709\u8DEF\u5F84\u5747\u4E3A vault \u76F8\u5BF9\u8DEF\u5F84\u3002\u65B0\u5EFA\u7B14\u8BB0\u9ED8\u8BA4\u4F7F\u7528 Markdown\uFF0C\u9002\u5F53\u4F7F\u7528\u6807\u9898\u3001\u5217\u8868\u548C [[wikilink]]\u3002
- \u7528\u7528\u6237\u7684\u8BED\u8A00\u56DE\u590D\uFF1B\u5DE5\u5177\u6267\u884C\u7ED3\u679C\u4E0D\u8981\u539F\u6837\u7C98\u8D34\uFF0C\u63D0\u70BC\u540E\u518D\u8BB2\u3002` : `You are an agent inside an Obsidian vault. Use the provided tools to search, read, create and edit the user's notes.
- Always ground claims about notes in tool results; never invent note contents.
- Use edit_note with an exact, unique old_string; create_note for new files; append_note to add text.
- All paths are vault-relative. New notes are Markdown with sensible headings and [[wikilinks]].
- Reply in the user's language; summarize tool output instead of pasting it raw.`);
    const ctx = [];
    ctx.push(zhMode ? `\u5E93\u540D\uFF1A${this.app.vault.getName()}` : `Vault: ${this.app.vault.getName()}`);
    ctx.push(zhMode ? `\u4ECA\u5929\u65E5\u671F\uFF1A${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}` : `Today: ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}`);
    if (s.autoContext) {
      ctx.push(zhMode ? `\u5F53\u524D\u6253\u5F00\u7684\u7B14\u8BB0\uFF1A${active ? active.path : this.st("noActiveNote")}` : `Active note: ${active ? active.path : "(none)"}`);
    }
    const search = resolveSearch(this.searchSettings());
    if (search.tool) {
      ctx.push(zhMode ? `\u8054\u7F51\u641C\u7D22\uFF1A\u9700\u8981\u6700\u65B0\u4FE1\u606F\u6216\u5E93\u5916\u77E5\u8BC6\u65F6\uFF0C\u5148\u8C03\u7528 web_search \u5DE5\u5177\uFF0C\u518D\u57FA\u4E8E\u68C0\u7D22\u7ED3\u679C\u56DE\u7B54\uFF0C\u5E76\u7ED9\u51FA\u7528\u5230\u7684\u6765\u6E90\u94FE\u63A5\u3002\u4ECA\u5929\u662F ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}\u3002` : `Web search: for current information or anything outside the vault, call the web_search tool first, then answer from the results and cite the source links. Today is ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}.`);
    } else if (search.native) {
      ctx.push(zhMode ? "\u8054\u7F51\u641C\u7D22\uFF1A\u5F53\u524D\u670D\u52A1\u5546\u5DF2\u5185\u7F6E\u8054\u7F51\uFF0C\u53EF\u4EE5\u76F4\u63A5\u56DE\u7B54\u9700\u8981\u5B9E\u65F6\u4FE1\u606F\u7684\u95EE\u9898\u3002" : "Web search: native search is enabled for this provider, so you can answer live questions directly.");
    }
    return base + "\n\n" + ctx.join("\n");
  }
  /** Current web-search configuration, as the pure `search.ts` helpers expect it. */
  searchSettings() {
    const s = this.plugin.settings;
    return {
      mode: s.searchMode,
      providerId: s.providerId,
      apiKey: s.searchApiKey,
      maxResults: s.searchMaxResults,
      depth: s.searchDepth
    };
  }
  confirmWrite(summary) {
    const s = this.plugin.settings;
    if (s.autoApprove)
      return Promise.resolve(true);
    return new Promise((resolve) => {
      const bar = this.msgsEl.createDiv({ cls: "va-confirm" });
      bar.createSpan({ text: this.st("confirmTitle") + " \u2014 " + summary });
      const row = bar.createDiv({ cls: "va-confirm-row" });
      const yes = row.createEl("button", { cls: "mod-cta", text: this.st("confirmAllow") });
      const no = row.createEl("button", { text: this.st("confirmDeny") });
      const done = (v) => {
        bar.remove();
        resolve(v);
      };
      yes.addEventListener("click", () => done(true));
      no.addEventListener("click", () => done(false));
      this.scrollBottom();
    });
  }
  async send() {
    if (this.running)
      return;
    const s = this.plugin.settings;
    if (!s.apiKey.trim()) {
      new import_obsidian2.Notice(this.st("needApiKey"));
      this.plugin.openSettings();
      return;
    }
    const input = this.inputEl.value.trim();
    if (!input)
      return;
    this.inputEl.value = "";
    this.running = true;
    this.abort = new AbortController();
    this.stopBtn.disabled = false;
    this.sendBtn.disabled = true;
    this.renderUserBubble(input);
    this.messages.push({ role: "user", content: input });
    const history = this.plugin.history;
    history.user(input);
    if (this.messages[0]?.role !== "system") {
      this.messages.unshift({ role: "system", content: this.buildSystemPrompt() });
    } else {
      this.messages[0].content = this.buildSystemPrompt();
    }
    const stream = this.beginStreamingBubble();
    const proxy = s.proxyUrl.trim();
    const fetchImpl = proxy ? makeProxyFetch(proxy) : (url, init) => window.fetch(url, init);
    const post = proxy ? async (url, headers, body) => {
      const r = await fetchImpl(url, { method: "POST", headers, body });
      return { status: r.status, body: await r.text() };
    } : (url, headers, body) => this.plugin.fallbackPost(url, headers, body);
    const searchPost = (url, headers, body) => withTimeout(post(url, headers, body), 2e4, "web search");
    const search = resolveSearch(this.searchSettings());
    const tools = buildToolDefs();
    if (search.tool)
      tools.push(buildWebSearchToolDef());
    const vaultExecutor = new VaultToolExecutor(this.app, () => this.app.workspace.getActiveFile()?.path ?? null);
    const searchExecutor = createWebSearchExecutor(searchPost, () => this.searchSettings());
    const executor = {
      execute: (name, args) => name === WEB_SEARCH_TOOL_NAME ? searchExecutor.execute(name, args) : vaultExecutor.execute(name, args)
    };
    const chipQueue = [];
    const toolStartedAt = /* @__PURE__ */ new Map();
    try {
      const { text, reasoning, hitCap } = await runAgentLoop({
        baseUrl: s.baseUrl,
        apiKey: s.apiKey,
        model: s.model,
        temperature: s.temperature,
        maxTokens: s.maxTokens,
        maxIterations: s.maxIterations,
        messages: this.messages,
        tools,
        executor,
        nativeSearch: search.native ?? void 0,
        passthroughTools: search.native?.passthrough,
        onSearchFallback: () => new import_obsidian2.Notice(this.st("searchFallback")),
        signal: this.abort.signal,
        confirmWrite: (summary) => this.confirmWrite(summary),
        fetchImpl,
        fallbackPost: post,
        onText: (d) => stream.push(d),
        onReasoning: (d) => stream.pushReasoning(d),
        onToolStart: (call) => {
          toolStartedAt.set(call.id, Date.now());
          history.toolCall(call);
          chipQueue.push(this.addToolChip(call));
        },
        onToolDone: (call, result) => {
          history.toolResult(call, result, Date.now() - (toolStartedAt.get(call.id) ?? Date.now()));
          const chip = chipQueue.shift();
          if (chip)
            this.completeToolChip(chip, result);
        }
      });
      const reply = text.trim() ? text : hitCap ? this.st("maxIterNoAnswer") : this.st("emptyReply");
      stream.finish(reply, reasoning);
      if (hitCap)
        new import_obsidian2.Notice(this.st("maxIterReached"));
      this.messages.push({ role: "assistant", content: reply });
      history.assistant(reply, reasoning);
    } catch (e) {
      const aborted = this.abort.signal.aborted;
      const msg = aborted ? s.lang === "zh" ? "\uFF08\u5DF2\u505C\u6B62\uFF09" : "(stopped)" : `${this.st("errPrefix")}: ${e instanceof Error ? e.message : String(e)}`;
      stream.finish(msg, "");
      this.messages.push({ role: "assistant", content: msg });
      history.error(msg);
      if (!aborted)
        new import_obsidian2.Notice(msg.slice(0, 200));
    } finally {
      this.running = false;
      this.stopBtn.disabled = true;
      this.sendBtn.disabled = false;
      void this.plugin.saveHistory(this.messages);
    }
  }
};
function formatStamp(iso) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime()))
    return "";
  const pad = (n) => String(n).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

// main.ts
var PROVIDERS = [
  { id: "deepseek", label: "DeepSeek \u6DF1\u5EA6\u6C42\u7D22", baseUrl: "https://api.deepseek.com/v1", models: ["deepseek-chat", "deepseek-reasoner"] },
  { id: "glm", label: "\u667A\u8C31 GLM (bigmodel.cn)", baseUrl: "https://open.bigmodel.cn/api/paas/v4", models: ["glm-4.6", "glm-4.5-air"], hint: "\u6A21\u578B ID \u4EE5 bigmodel.cn \u63A7\u5236\u53F0\u4E3A\u51C6" },
  { id: "zai", label: "Z.ai (GLM \u6D77\u5916\u7248)", baseUrl: "https://api.z.ai/api/paas/v4", models: ["glm-4.6", "glm-4.5-air"] },
  { id: "kimi", label: "Kimi (Moonshot \u6708\u4E4B\u6697\u9762)", baseUrl: "https://api.moonshot.cn/v1", models: ["kimi-k2-turbo-preview", "kimi-k2-preview", "moonshot-v1-32k"], hint: "K \u7CFB\u5217\u6A21\u578B ID \u4EE5 platform.moonshot.cn \u4E3A\u51C6" },
  { id: "qwen", label: "\u901A\u4E49 Qwen (DashScope \xB7 Qoder \u540C\u6E90)", baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", models: ["qwen3-coder-plus", "qwen-plus", "qwen-max"] },
  { id: "ark", label: "\u706B\u5C71\u65B9\u821F Ark (\u8C46\u5305 \xB7 Trae \u540C\u6E90)", baseUrl: "https://ark.cn-beijing.volces.com/api/v3", models: ["doubao-seed-1-6-250615"], hint: "\u65B9\u821F\u9700\u586B\u63A8\u7406\u63A5\u5165\u70B9 ID\uFF08ep-xxx\uFF09\u6216\u6A21\u578B ID\uFF0C\u4EE5\u706B\u5C71\u63A7\u5236\u53F0\u4E3A\u51C6" },
  { id: "hunyuan", label: "\u817E\u8BAF\u6DF7\u5143 Hunyuan (WorkBuddy \u540C\u6E90)", baseUrl: "https://api.hunyuan.cloud.tencent.com/v1", models: ["hunyuan-turbos-latest", "hunyuan-t1-latest"] },
  { id: "hermes", label: "Hermes (Nous Research)", baseUrl: "https://inference-api.nousresearch.com/v1", models: ["Hermes-4-405B", "Hermes-4-70B"], hint: "\u4E5F\u53EF\u7528 OpenRouter \u8F6C\u53D1\uFF08\u9009 OpenRouter \u5E76\u586B nousresearch/hermes-4-405b\uFF09" },
  { id: "openrouter", label: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1", models: ["nousresearch/hermes-4-405b", "deepseek/deepseek-chat-v3.1"] },
  { id: "custom", label: "\u81EA\u5B9A\u4E49 OpenAI \u517C\u5BB9\u7AEF\u70B9", baseUrl: "", models: [], hint: "\u586B\u5199\u4EFB\u610F OpenAI \u517C\u5BB9 Base URL \u4E0E\u6A21\u578B ID" }
];
var DEFAULT_SETTINGS = {
  providerId: "deepseek",
  baseUrl: "https://api.deepseek.com/v1",
  apiKey: "",
  proxyUrl: "",
  model: "deepseek-chat",
  temperature: 0.7,
  maxTokens: 8192,
  maxIterations: 12,
  autoContext: true,
  autoApprove: false,
  systemPrompt: "",
  lang: "zh",
  history: [],
  sessionId: "",
  searchMode: "off",
  searchApiKey: "",
  searchMaxResults: 5,
  searchDepth: "basic"
};
var VaultAgentPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.recorder = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_AGENT, (leaf) => new AgentView(leaf, this));
    this.addRibbonIcon("bot-message-square", t(this.settings.lang, "viewName"), () => void this.revealAgent());
    this.addCommand({ id: "open-agent", name: "\u6253\u5F00\u667A\u80FD\u4F53 / open agent", callback: () => void this.revealAgent() });
    this.addSettingTab(new VASettingTab(this.app, this));
  }
  onunload() {
  }
  /** Open (or reveal) the agent view; safe to call repeatedly. */
  async revealAgent() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_AGENT);
    if (existing.length) {
      await this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false) ?? this.app.workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE_AGENT, active: true });
    await this.app.workspace.revealLeaf(leaf);
  }
  openSettings() {
    const setting = this.app.setting;
    setting.open();
    setting.openTabById(this.manifest.id);
  }
  currentModelLabel() {
    return this.settings.model || this.settings.baseUrl || "not configured";
  }
  /** Non-streaming fallback used when direct fetch streaming fails (e.g. CORS). */
  /**
   * Non-streaming POST through Obsidian's `requestUrl` (bypasses CORS, works on
   * mobile). It ignores AbortSignal and has no timeout, so cap it here: a stalled
   * endpoint must surface as an error the chat can report, not as a hung turn.
   */
  async fallbackPost(url, headers, body, timeoutMs = 12e4) {
    const res = await withTimeout(
      (0, import_obsidian3.requestUrl)({ url, method: "POST", headers, body, throw: false }),
      timeoutMs,
      "request"
    );
    return { status: res.status, body: res.text };
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data ?? {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  loadHistory() {
    const h = this.settings.history;
    return Array.isArray(h) ? h.slice(-40) : [];
  }
  async saveHistory(messages) {
    this.settings.history = messages.filter((m) => m.role !== "system").slice(-40);
    await this.saveData(this.settings);
  }
  /** `history.jsonl` sits next to `data.json`, inside the plugin folder. */
  historyPath() {
    const dir = this.manifest.dir ?? `.obsidian/plugins/${this.manifest.id}`;
    return (0, import_obsidian3.normalizePath)(`${dir}/history.jsonl`);
  }
  /**
   * Durable transcript used by `tools/history_db.py`. Unlike `saveHistory`
   * (last 40 messages, overwritten each turn) this is append-only and keeps
   * timestamps, session ids and tool calls.
   */
  get history() {
    if (!this.recorder) {
      this.recorder = this.newRecorder(this.settings.sessionId || this.startSession());
    }
    return this.recorder;
  }
  /** Rotate the session id so a new chat is a separate session in the database. */
  startSession() {
    const id = newSessionId();
    this.settings.sessionId = id;
    this.recorder = null;
    void this.saveSettings();
    return id;
  }
  /**
   * Continue an existing session picked in the history panel: new events append
   * to it, with seq/turn picking up where its transcript left off.
   */
  resumeSession(sessionId, cursor) {
    this.settings.sessionId = sessionId;
    this.recorder = this.newRecorder(sessionId, cursor);
    void this.saveSettings();
  }
  /** Raw `history.jsonl` text; empty string when nothing has been recorded yet. */
  async readHistoryText() {
    try {
      return await this.app.vault.adapter.read(this.historyPath());
    } catch {
      return "";
    }
  }
  newRecorder(session, cursor = { seq: 0, turn: 0 }) {
    return new HistoryRecorder(this.app.vault.adapter, this.historyPath(), session, () => this.historyMeta(), cursor);
  }
  historyMeta() {
    return {
      vault: this.app.vault.getName(),
      provider: this.settings.providerId,
      model: this.settings.model
    };
  }
};
var VASettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  st(key) {
    return t(this.plugin.settings.lang, key);
  }
  /**
   * Declarative settings (Obsidian 1.13+): makes settings searchable.
   * display() below still renders for older Obsidian versions.
   */
  getSettingDefinitions() {
    const s = this.plugin.settings;
    const providerHint = PROVIDERS.find((p) => p.id === s.providerId)?.hint;
    return [
      {
        name: this.st("language"),
        desc: this.st("languageDesc"),
        control: { type: "dropdown", key: "lang", options: { zh: "\u4E2D\u6587", en: "English" } }
      },
      {
        name: this.st("provider"),
        desc: this.st("providerDesc") + (providerHint ? "\n\u2139\uFE0F " + providerHint : ""),
        control: { type: "dropdown", key: "providerId", options: Object.fromEntries(PROVIDERS.map((p) => [p.id, p.label])) }
      },
      {
        name: this.st("baseUrl"),
        control: { type: "text", key: "baseUrl", placeholder: "https://api.example.com/v1" }
      },
      {
        name: this.st("apiKey"),
        desc: this.st("apiKeyDesc"),
        control: { type: "text", key: "apiKey", placeholder: "sk-\u2026" }
      },
      {
        name: this.st("proxy"),
        desc: this.st("proxyDesc"),
        control: { type: "text", key: "proxyUrl", placeholder: "http://127.0.0.1:9000" }
      },
      {
        name: this.st("model"),
        desc: this.st("modelDesc"),
        control: { type: "text", key: "model" }
      },
      {
        name: this.st("modelPreset"),
        searchable: false,
        visible: () => !!PROVIDERS.find((p) => p.id === this.plugin.settings.providerId)?.models.length,
        render: (setting) => {
          const preset = PROVIDERS.find((p) => p.id === this.plugin.settings.providerId);
          for (const m of preset?.models ?? []) {
            const btn = setting.controlEl.createEl("button", { text: m });
            if (m === this.plugin.settings.model)
              btn.addClass("va-chip-active");
            btn.addEventListener("click", () => {
              this.plugin.settings.model = m;
              void this.plugin.saveSettings();
              setting.controlEl.querySelectorAll("button").forEach((b) => b.removeClass("va-chip-active"));
              btn.addClass("va-chip-active");
            });
          }
          return () => setting.controlEl.empty();
        }
      },
      {
        name: this.st("temperature"),
        control: { type: "slider", key: "temperature", min: 0, max: 2, step: 0.1 }
      },
      {
        name: this.st("maxTokens"),
        control: {
          type: "number",
          key: "maxTokens",
          step: 1,
          validate: (v) => typeof v === "number" && v > 0 ? void 0 : "must be a positive number"
        }
      },
      {
        name: this.st("maxIterations"),
        control: {
          type: "number",
          key: "maxIterations",
          step: 1,
          validate: (v) => typeof v === "number" && v > 0 ? void 0 : "must be a positive number"
        }
      },
      {
        name: this.st("autoContext"),
        desc: this.st("autoContextDesc"),
        control: { type: "toggle", key: "autoContext" }
      },
      {
        name: this.st("autoApprove"),
        desc: this.st("autoApproveDesc"),
        control: { type: "toggle", key: "autoApprove" }
      },
      {
        name: this.st("systemPrompt"),
        desc: this.st("systemPromptDesc"),
        control: { type: "textarea", key: "systemPrompt", rows: 4 }
      },
      ...this.searchSettingDefinitions()
    ];
  }
  /** Web-search settings; shared by the declarative and the legacy settings UI. */
  searchSettingDefinitions() {
    const usesTool = () => ["auto", "tool"].includes(this.plugin.settings.searchMode);
    const nativeUnsupported = () => {
      const s = this.plugin.settings;
      return s.searchMode === "native" && !nativeSearchFor(s.providerId, s.searchMaxResults);
    };
    return [
      {
        name: this.st("searchMode"),
        desc: this.st("searchModeDesc"),
        control: {
          type: "dropdown",
          key: "searchMode",
          options: {
            off: this.st("searchModeOff"),
            auto: this.st("searchModeAuto"),
            native: this.st("searchModeNative"),
            tool: this.st("searchModeTool")
          }
        }
      },
      {
        name: this.st("searchApiKey"),
        desc: this.st("searchApiKeyDesc"),
        visible: usesTool,
        control: { type: "text", key: "searchApiKey" }
      },
      {
        name: this.st("searchMaxResults"),
        visible: usesTool,
        control: {
          type: "number",
          key: "searchMaxResults",
          step: 1,
          validate: (v) => typeof v === "number" && v >= 1 && v <= 20 ? void 0 : "must be 1-20"
        }
      },
      {
        name: this.st("searchDepth"),
        visible: usesTool,
        control: {
          type: "dropdown",
          key: "searchDepth",
          options: { basic: this.st("searchDepthBasic"), advanced: this.st("searchDepthAdvanced") }
        }
      },
      {
        // Description-only row: no control, just the explanation.
        name: this.st("searchUnsupported"),
        searchable: false,
        visible: nativeUnsupported,
        render: (setting) => {
          setting.settingEl.addClass("va-hint");
          return () => setting.settingEl.removeClass("va-hint");
        }
      }
    ];
  }
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    const s = this.plugin.settings;
    s[key] = value;
    if (key === "providerId" && typeof value === "string") {
      const preset = PROVIDERS.find((p) => p.id === value);
      if (preset) {
        s.baseUrl = preset.baseUrl;
        if (preset.models.length)
          s.model = preset.models[0];
      }
    }
    await this.plugin.saveSettings();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const s = this.plugin.settings;
    let searchEl = null;
    new import_obsidian3.Setting(containerEl).setName(this.st("settingsHeading")).setHeading();
    new import_obsidian3.Setting(containerEl).setName(this.st("language")).setDesc(this.st("languageDesc")).addDropdown((d) => d.addOption("zh", "\u4E2D\u6587").addOption("en", "English").setValue(s.lang).onChange(async (v) => {
      s.lang = v;
      await this.plugin.saveSettings();
    }));
    const providerNames = PROVIDERS.map((p) => [p.id, p.label]);
    new import_obsidian3.Setting(containerEl).setName(this.st("provider")).setDesc(this.st("providerDesc")).addDropdown((d) => {
      for (const [id, label] of providerNames)
        d.addOption(id, label);
      d.setValue(s.providerId).onChange(async (v) => {
        const preset = PROVIDERS.find((p) => p.id === v);
        if (preset) {
          s.baseUrl = preset.baseUrl;
          if (preset.models.length)
            s.model = preset.models[0];
        }
        s.providerId = v;
        await this.plugin.saveSettings();
        this.renderProviderExtras(containerEl);
        if (searchEl)
          this.renderSearchSettings(searchEl);
      });
    });
    new import_obsidian3.Setting(containerEl).setName(this.st("baseUrl")).addText((tx) => tx.setValue(s.baseUrl).onChange(async (v) => {
      s.baseUrl = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("apiKey")).setDesc(this.st("apiKeyDesc")).addText((tx) => {
      tx.inputEl.type = "password";
      tx.setValue(s.apiKey).onChange(async (v) => {
        s.apiKey = v.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName(this.st("proxy")).setDesc(this.st("proxyDesc")).addText((tx) => tx.setValue(s.proxyUrl).onChange(async (v) => {
      s.proxyUrl = v.trim();
      await this.plugin.saveSettings();
    }));
    const modelSetting = new import_obsidian3.Setting(containerEl).setName(this.st("model")).setDesc(this.st("modelDesc"));
    modelSetting.addText((tx) => tx.setValue(s.model).onChange(async (v) => {
      s.model = v.trim();
      await this.plugin.saveSettings();
    }));
    this.renderProviderExtras(containerEl);
    new import_obsidian3.Setting(containerEl).setName(this.st("temperature")).addSlider((sl) => sl.setLimits(0, 2, 0.1).setValue(s.temperature).onChange(async (v) => {
      s.temperature = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("maxTokens")).addText((tx) => tx.setValue(String(s.maxTokens)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (n > 0) {
        s.maxTokens = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("maxIterations")).addText((tx) => tx.setValue(String(s.maxIterations)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (n > 0) {
        s.maxIterations = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("autoContext")).setDesc(this.st("autoContextDesc")).addToggle((tg) => tg.setValue(s.autoContext).onChange(async (v) => {
      s.autoContext = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("autoApprove")).setDesc(this.st("autoApproveDesc")).addToggle((tg) => tg.setValue(s.autoApprove).onChange(async (v) => {
      s.autoApprove = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(this.st("systemPrompt")).setDesc(this.st("systemPromptDesc")).addTextArea((ta) => ta.setValue(s.systemPrompt).onChange(async (v) => {
      s.systemPrompt = v;
      await this.plugin.saveSettings();
    }));
    searchEl = containerEl.createDiv({ cls: "va-search-settings" });
    this.renderSearchSettings(searchEl);
  }
  /**
   * Web-search settings for the legacy (pre-1.13) settings UI. Re-rendered in
   * place when the mode or provider changes, because several rows are conditional.
   */
  renderSearchSettings(el) {
    const s = this.plugin.settings;
    el.empty();
    const usesTool = () => ["auto", "tool"].includes(s.searchMode);
    const rerender = () => this.renderSearchSettings(el);
    new import_obsidian3.Setting(el).setName(this.st("searchMode")).setDesc(this.st("searchModeDesc")).addDropdown((d) => d.addOption("off", this.st("searchModeOff")).addOption("auto", this.st("searchModeAuto")).addOption("native", this.st("searchModeNative")).addOption("tool", this.st("searchModeTool")).setValue(s.searchMode).onChange(async (v) => {
      s.searchMode = v;
      await this.plugin.saveSettings();
      rerender();
    }));
    if (s.searchMode === "native" && !nativeSearchFor(s.providerId, s.searchMaxResults)) {
      const hint = new import_obsidian3.Setting(el).setClass("va-hint");
      hint.nameEl.setText("\u26A0\uFE0F " + this.st("searchUnsupported"));
    }
    if (!usesTool())
      return;
    new import_obsidian3.Setting(el).setName(this.st("searchApiKey")).setDesc(this.st("searchApiKeyDesc")).addText((tx) => {
      tx.inputEl.type = "password";
      tx.setValue(s.searchApiKey).onChange(async (v) => {
        s.searchApiKey = v.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(el).setName(this.st("searchMaxResults")).addText((tx) => tx.setValue(String(s.searchMaxResults)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (n >= 1 && n <= 20) {
        s.searchMaxResults = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(el).setName(this.st("searchDepth")).addDropdown((d) => d.addOption("basic", this.st("searchDepthBasic")).addOption("advanced", this.st("searchDepthAdvanced")).setValue(s.searchDepth).onChange(async (v) => {
      s.searchDepth = v;
      await this.plugin.saveSettings();
    }));
  }
  /** Provider hint + model preset chips; re-rendered in place when the provider changes. */
  renderProviderExtras(containerEl) {
    const s = this.plugin.settings;
    const preset = PROVIDERS.find((p) => p.id === s.providerId);
    if (preset?.hint) {
      const hint = new import_obsidian3.Setting(containerEl).setClass("va-hint");
      hint.nameEl.setText("\u2139\uFE0F " + preset.hint);
    }
    if (!preset?.models.length)
      return;
    const presets = new import_obsidian3.Setting(containerEl).setName(this.st("modelPreset")).setClass("va-model-chips");
    for (const m of preset.models) {
      presets.addButton((b) => {
        b.setButtonText(m);
        if (s.model === m)
          b.buttonEl.addClass("va-chip-active");
        b.onClick(async () => {
          s.model = m;
          await this.plugin.saveSettings();
          presets.controlEl.querySelectorAll("button").forEach((el) => el.removeClass("va-chip-active"));
          b.buttonEl.addClass("va-chip-active");
        });
      });
    }
  }
};
